[package]
name = "hello_world_simple"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
ratatui = { version = "0.29", default-features = false }
egui_ratatui = { path = "../" }
